# Generated by Django 6.1.1 on 2026-09-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
