# Generated by Django 6.1.1 on 2026-09-07 15:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attendancesession_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='session_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
