# Generated by Django 6.1.1 on 2026-09-30 04:19

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_attendancesession_teacher_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='qr_token_expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
