# Generated by Django 6.1.1 on 2026-09-30 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attendancesession_qr_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancesession',
            name='qr_token',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='qr_token_expires_at',
        ),
    ]
