# Generated by Django 6.1.1 on 2026-09-30 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_attendancesession_qr_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='qr_token_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
