# Generated by Django 6.1.1 on 2026-09-30 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_attendancesession_qr_token_expires_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beacon',
        ),
    ]
